before_install:
  - sudo apt-get install -y software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
  - sudo add-apt-repository 'deb [arch=amd64] http://mariadb.mirrors.ovh.net/MariaDB/repo/10.3/ubuntu bionic main'
  - sudo apt update -qq
  - sudo apt-get install -y libmariadb3 libmariadbclient18 libmysqlclient18 libpq5
addons:
  apt:
    update: true
dist: bionic
language: python
python:
  - "3.5"
env:
  matrix:
  - TOXENV=py3
  - TOXENV=pep8

install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - bash -ex .travis-ci.sh
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov