before_install:
  - sudo apt-get install -y libmariadbclient-dev libsqlite3-dev libpq-dev
dist: xenial
language: python
python:
  - "3.5"
env:
  matrix:
  - TOXENV=py3
  - TOXENV=pep8

install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - bash -ex .travis-ci.sh
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov